# Generated by Django 3.2.25 on 2024-06-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taytoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('productCode', models.CharField(blank=True, max_length=254, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('barcode', models.CharField(blank=True, max_length=254, null=True)),
                ('caseCount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tayto Product',
                'verbose_name_plural': 'Tayto Products',
            },
        ),
    ]
