# Generated by Django 3.2.25 on 2024-06-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tayto', '0005_auto_20240625_1221'),
        ('orderForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taytoorder',
            options={},
        ),
        migrations.AddField(
            model_name='taytoorder',
            name='products',
            field=models.ManyToManyField(related_name='orders', to='tayto.taytoProduct'),
        ),
    ]
