# Generated by Django 3.2.25 on 2024-06-26 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orderForm', '0002_auto_20240626_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='taytoorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
