# Generated by Django 3.2.25 on 2024-06-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderForm', '0002_auto_20240625_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taytoorder',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='taytoorder',
            name='caseCount',
        ),
        migrations.RemoveField(
            model_name='taytoorder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='taytoorder',
            name='productCode',
        ),
        migrations.RemoveField(
            model_name='taytoorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='taytoorder',
            name='weight',
        ),
    ]
