# Generated by Django 3.2.25 on 2024-07-02 16:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('walkers', '0001_initial'),
        ('orderForm', '0003_taytoorder_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='walkersOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WalkersOrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderForm.walkersorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walkers.walkersproduct')),
            ],
        ),
        migrations.AddField(
            model_name='walkersorder',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='orderForm.WalkersOrderProduct', to='walkers.walkersProduct'),
        ),
    ]
