# Generated by Django 3.2.25 on 2024-06-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taytoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('productCode', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('bracode', models.IntegerField(blank=True, null=True)),
                ('caseCount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
